import {WordType} from "../WordType";

export const l1: WordType[] = [
    {
        en: 'Peter',
        ru: 'Пётр',
        tr: 'pi:ta:_r',
        de: 'имя',
        er: [],
    },
    {
        en: 'Joni',
        ru: 'Джони',
        tr: 'ʤoni',
        de: 'имя',
        er: ['James', 'Jacob'],
    },
    {
        en: 'Kate',
        ru: 'Катя',
        tr: 'keɪt',
        de: 'имя',
        er: [],
    },
    {
        en: 'Gary',
        ru: 'Гари',
        tr: 'hʌri',
        de: 'имя',
        er: [],
    },
    {
        en: 'I',
        ru: 'я',
        tr: 'aɪ',
        de: 'я',
        er: [],
    },
    {
        en: 'am',
        ru: 'есть/являться',
        tr: 'æm',
        de: 'непереводимое',
        er: [],
    },
    {
        en: 'robot',
        ru: 'робот',
        tr: 'rəʊ.bɒt',
        de: 'механизм',
        er: [],
    },
    {
        en: 'Betty',
        ru: 'Бэтти',
        tr: 'betɪ',
        de: 'имя',
        er: [],
    },
    {
        en: 'James',
        ru: 'Джеймс',
        tr: 'ʤeɪmz',
        de: 'имя',
        er: [],
    },
    {
        en: 'Jacob',
        ru: 'Джейкоб',
        tr: 'ʤeɪkəb',
        de: 'имя',
        er: [],
    },
    {
        en: 'A',
        ru: 'а',
        tr: 'eɪ',
        de: 'буква',
        er: ['I', 'R'],
    },
    {
        en: 'apple',
        ru: 'яблоко',
        tr: 'æp.l̩',
        de: 'фрукт',
        er: ['April', 'apply'],
    },
    {
        en: 'April',
        ru: 'Апрель',
        tr: 'eɪprəl̩',
        de: 'месяц',
        er: [],
    },
    {
        en: 'apply',
        ru: 'применять',
        tr: 'əˈplaɪ',
        de: 'действие',
        er: [],
    },
    {
        en: 'I am Ignat',
        ru: 'я Игнат',
        tr: 'aɪ æm Игнат',
        de: 'предложение',
        er: [],
    },

]